# Generated by Django 3.2 on 2021-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAmazonV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.TextField(blank=True, db_column='Uniq Id', null=True)),
                ('product_name', models.TextField(blank=True, db_column='Product Name', null=True)),
                ('category', models.TextField(blank=True, db_column='Category', null=True)),
                ('selling_price', models.FloatField(blank=True, db_column='Selling Price', null=True)),
                ('image', models.TextField(blank=True, db_column='Image', null=True)),
                ('stock', models.IntegerField(blank=True, db_column='Stock', null=True)),
                ('model_number', models.TextField(blank=True, db_column='Model Number', null=True)),
                ('variants', models.TextField(blank=True, db_column='Variants', null=True)),
                ('about_product', models.TextField(blank=True, db_column='About Product', null=True)),
                ('product_specification', models.TextField(blank=True, db_column='Product Specification', null=True)),
                ('technical_details', models.TextField(blank=True, db_column='Technical Details', null=True)),
                ('product_url', models.TextField(blank=True, db_column='Product Url', null=True)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('shiping', models.TextField(blank=True, db_column='Shiping', null=True)),
                ('discount_percentage', models.IntegerField(blank=True, db_column='discount percentage', null=True)),
            ],
            options={
                'db_table': 'final_amazon_v2',
                'managed': True,
            },
        ),
    ]
